services:
  frontend:
    container_name: frontend-service
    build: ./frontend
    ports:
      - "5000:5000"
    depends_on:
      - catalog-service
      - order-service

  catalog-service:
    container_name: catalog-service
    build: ./catalog_service
    ports:
      - "5003:5003"

  order-service:
    container_name: order-service
    build: ./order_service  
    ports:
      - "5002:5002"